# Generated by Django 5.2.3 on 2025-06-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"),
        ),
    ]
