# Generated by Django 5.2.3 on 2025-06-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_url_payment_stripe_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Сумма оплаты"),
        ),
    ]
