# Generated by Django 5.2.3 on 2025-06-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="lessons/img"),
        ),
    ]
