# Generated by Django 5.2.3 on 2025-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Цена за курс"),
        ),
    ]
