# Generated by Django 5.2.3 on 2025-06-27 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="subscribed_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
